name: Dependabot
on:
  workflow_dispatch:
  schedule:
    - cron: '30 9 * * 1,4' # At 09:30 on Monday and Thursday.

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: carwow/dependabot-lein-runner@main
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}

  notify:
    runs-on: ubuntu-latest
    needs: update
    if: always()
    steps:
      - name: Get workflow information
        id: get-workflow-info
        uses: technote-space/workflow-conclusion-action@v3

      - name: Send GitHub Action trigger data to Slack workflow
        if: ${{ steps.get-workflow-info.outputs.conclusion != 'success' }}
        id: slack
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: |
            {
              "repo_name": "${{ github.respository }}",
              "workflow_name": "${{ github.workflow }}",
              "workflow_run_url": "${{ github.server_url}}/${{ github.repository}}/actions/runs/${{ github.run_id }}"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
